/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TradingPairService } from "../tradingPair.service";
import { TradingPairCreateInput } from "./TradingPairCreateInput";
import { TradingPair } from "./TradingPair";
import { TradingPairFindManyArgs } from "./TradingPairFindManyArgs";
import { TradingPairWhereUniqueInput } from "./TradingPairWhereUniqueInput";
import { TradingPairUpdateInput } from "./TradingPairUpdateInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";

export class TradingPairControllerBase {
  constructor(protected readonly service: TradingPairService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TradingPair })
  async createTradingPair(
    @common.Body() data: TradingPairCreateInput
  ): Promise<TradingPair> {
    return await this.service.createTradingPair({
      data: data,
      select: {
        baseCurrency: true,
        createdAt: true,
        id: true,
        quoteCurrency: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TradingPair] })
  @ApiNestedQuery(TradingPairFindManyArgs)
  async tradingPairs(@common.Req() request: Request): Promise<TradingPair[]> {
    const args = plainToClass(TradingPairFindManyArgs, request.query);
    return this.service.tradingPairs({
      ...args,
      select: {
        baseCurrency: true,
        createdAt: true,
        id: true,
        quoteCurrency: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TradingPair })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async tradingPair(
    @common.Param() params: TradingPairWhereUniqueInput
  ): Promise<TradingPair | null> {
    const result = await this.service.tradingPair({
      where: params,
      select: {
        baseCurrency: true,
        createdAt: true,
        id: true,
        quoteCurrency: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TradingPair })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTradingPair(
    @common.Param() params: TradingPairWhereUniqueInput,
    @common.Body() data: TradingPairUpdateInput
  ): Promise<TradingPair | null> {
    try {
      return await this.service.updateTradingPair({
        where: params,
        data: data,
        select: {
          baseCurrency: true,
          createdAt: true,
          id: true,
          quoteCurrency: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TradingPair })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTradingPair(
    @common.Param() params: TradingPairWhereUniqueInput
  ): Promise<TradingPair | null> {
    try {
      return await this.service.deleteTradingPair({
        where: params,
        select: {
          baseCurrency: true,
          createdAt: true,
          id: true,
          quoteCurrency: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: TradingPairWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        price: true,
        status: true,

        tradingPair: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  async connectOrders(
    @common.Param() params: TradingPairWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateTradingPair({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  async updateOrders(
    @common.Param() params: TradingPairWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateTradingPair({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  async disconnectOrders(
    @common.Param() params: TradingPairWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateTradingPair({
      where: params,
      data,
      select: { id: true },
    });
  }
}
